#!/usr/bin/env python3

import argparse
import cantools
import datetime
import os

from data_log import DataLog
from motec_log import MotecLog

# Maps metadata keys found in a log preamble (as exported by AiM loggers) to the MoTeC log metadata
# fields they correspond to. These are only used when the matching command line argument is omitted.
METADATA_MAP = {
    "Racer": "driver",
    "Vehicle": "vehicle_id",
    "Session": "venue_name",
    "Championship": "event_name",
    "Segment": "event_session",
    "Comment": "short_comment",
}

# Formats used by the "Date" and "Time" metadata entries, e.g. "Saturday, June 13, 2026", "3:04 PM"
DATE_FORMATS = ["%A, %B %d, %Y", "%B %d, %Y", "%Y-%m-%d", "%d/%m/%Y", "%m/%d/%Y"]
TIME_FORMATS = ["%I:%M %p", "%I:%M:%S %p", "%H:%M", "%H:%M:%S"]

def parse_metadata_datetime(metadata):
    """ Builds a datetime from the "Date" and "Time" metadata entries, returns None on failure. """
    date_text = metadata.get("Date")
    time_text = metadata.get("Time")

    if not isinstance(date_text, str) or not date_text:
        return None

    date = None
    for date_format in DATE_FORMATS:
        try:
            date = datetime.datetime.strptime(date_text, date_format)
            break
        except ValueError:
            continue

    if not date:
        return None

    if isinstance(time_text, str) and time_text:
        for time_format in TIME_FORMATS:
            try:
                time = datetime.datetime.strptime(time_text, time_format).time()
                return datetime.datetime.combine(date.date(), time)
            except ValueError:
                continue

    return date


DESCRIPTION = """Generates MoTeC .ld files from external log files generated by: CAN bus dumps, CSV
 files, or COBB Accessport CSV files"""

EPILOG = """The CAN bus log must be the same format as what is generated by 'candump' with the '-l'
option from the linux package can-utils. A MoTeC channel will be created for every signal in the
DBC file that has messages in the CAN log. The signal name and units will be directly copied from
the DBC file.

CSV files must have time as their first column. A MoTeC channel will be generated for all remaining
columns. Fields may be separated by commas, tabs, or semicolons. A row of units directly below the
header row is optional, when present the units will be assigned to each channel, otherwise channels
will not have any units. Channels do not need a value in every row, an empty field means that
channel was not updated at that timestamp.

CSV files may also begin with a preamble of "key","value" metadata rows, as exported by AiM data
loggers. The Racer, Vehicle, Session, Championship, Segment, Comment, Date, Time, and Sample Rate
entries will be used to populate the MoTeC log metadata and the resample frequency. Anything given
on the command line takes precedence over the values from the log.

COBB Accessport CSV logs are simply generated by starting a logging session on the accessport. A
MoTeC channel will be created for every channel logged, the name and units will be directly copied
over.

Note that MoTeC i2 will not show any channel data for a log with an empty driver, vehicle id,
venue, or session, so a placeholder is written for any of those which are not supplied.
"""

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=DESCRIPTION, epilog=EPILOG)
    parser.add_argument("log", type=str, help="Path to logfile")
    parser.add_argument("log_type", type=str, help="Type of log to process", \
        choices=["CAN", "CSV", "ACCESSPORT"])

    parser.add_argument("--output", type=str, \
        help="Name of output file, defaults to the same filename as 'log'")
    parser.add_argument("--frequency", type=float, \
        help="Fixed frequency to resample all channels at, defaults to the sample rate from the " \
        "log metadata if present, otherwise 20 Hz")
    parser.add_argument("--dbc", type=str, help="Path to DBC file, required if log type CAN")

    parser.add_argument("--driver", type=str, help="Motec log metadata field")
    parser.add_argument("--vehicle_id", type=str, help="Motec log metadata field")
    parser.add_argument("--vehicle_weight", type=int, help="Motec log metadata field")
    parser.add_argument("--vehicle_type", type=str, help="Motec log metadata field")
    parser.add_argument("--vehicle_comment", type=str, help="Motec log metadata field")
    parser.add_argument("--venue_name", type=str, help="Motec log metadata field")
    parser.add_argument("--event_name", type=str, help="Motec log metadata field")
    parser.add_argument("--event_session", type=str, help="Motec log metadata field")
    parser.add_argument("--long_comment", type=str, help="Motec log metadata field")
    parser.add_argument("--short_comment", type=str, help="Motec log metadata field")
    args = parser.parse_args()

    if args.log:
        args.log = os.path.expanduser(args.log)
    if args.dbc:
        args.dbc = os.path.expanduser(args.dbc)
    if args.output:
        args.output = os.path.expanduser(args.output)

    # Make sure our input files are valid
    if not os.path.isfile(args.log):
        print("ERROR: log file %s does not exist" % args.log)
        exit(1)

    if args.log_type == "CAN" and not os.path.isfile(args.dbc):
        print("ERROR: DBC file %s does not exist" % args.dbc)
        exit(1)

    print("Loading log...")
    with open(args.log, "r", errors="replace") as file:
        lines = file.readlines()

    # Create our data log from the input data
    data_log = DataLog()

    if args.log_type == "CAN":
        if not os.path.isfile(args.dbc):
            print("ERROR: DBC file %s does not exist" % args.dbc)
            exit(1)

        # Load the databse and log file
        print("Loading DBC...")
        can_db = cantools.database.load_file(args.dbc)

        print("Extracting data...")
        data_log.from_can_log(lines, can_db)
    elif args.log_type == "CSV":
        print("Extracting data...")
        data_log.from_csv_log(lines)
    elif args.log_type == "ACCESSPORT":
        print("Extracting data...")
        data_log.from_accessport_log(lines)

    if not data_log.channels:
        print("ERROR: Failed to find any channels in log data")
        exit(1)

    if data_log.metadata:
        print("Found log metadata:")
        for key, value in data_log.metadata.items():
            print("\t%s: %s" % (key, value))

    print("Parsed %.1fs log with %s channels:" % (data_log.duration(), len(data_log.channels)))
    for channel_name, channel in data_log.channels.items():
        print("\t%s" % channel)

    # Determine the resample frequency, preferring the command line argument, then the sample rate
    # from the log metadata
    frequency = args.frequency
    if not frequency:
        try:
            frequency = float(data_log.metadata.get("Sample Rate"))
            print("Using sample rate of %.1f Hz from log metadata" % frequency)
        except (TypeError, ValueError):
            frequency = 20.0

    # Resample all the channels to occur at a fixed frequency. We must do this because the data in
    # motec log expects a constant sample rate, it does not associate a timestamp to each individual
    # message in a channel.
    data_log.resample(frequency)

    print("Converting to MoTeC log...")

    motec_log = MotecLog()

    # Fill in the metadata fields from the log itself where we can, any values given on the command
    # line take precedence
    for key, field in METADATA_MAP.items():
        value = data_log.metadata.get(key)
        if isinstance(value, str) and value:
            setattr(motec_log, field, value)

    log_datetime = parse_metadata_datetime(data_log.metadata)
    if log_datetime:
        motec_log.datetime = log_datetime

    for field in ["driver", "vehicle_id", "vehicle_weight", "vehicle_type", "vehicle_comment", \
        "venue_name", "event_name", "event_session", "long_comment", "short_comment"]:
        value = getattr(args, field)
        if value is not None:
            setattr(motec_log, field, value)

    motec_log.initialize()
    motec_log.add_all_channels(data_log)

    print("Saving MoTeC log...")
    if args.output:
        ld_filename = os.path.splitext(args.output)[0] + ".ld"
    else:
        # Copy the path and name from the source file, but change the extension
        candump_dir, candump_filename = os.path.split(args.log)
        candump_filename = os.path.splitext(candump_filename)[0]
        ld_filename = os.path.join(candump_dir, candump_filename + ".ld")

    output_dir = os.path.dirname(ld_filename)
    if output_dir and not os.path.isdir(output_dir):
        print("Directory '%s' does not exist, will create it" % output_dir)
        os.makedirs(output_dir)

    motec_log.write(ld_filename)
    print("Done!")
